const networkOptions = [
  { label: 'Ethereum Mainnet', value: 1 },
  { label: 'Sepolia Testnet', value: 11155111 },
  { label: 'Holesky Testnet', value: 17000 },
  { label: 'Hoodi Testnet', value: 560048 },
  { label: 'Abstract Mainnet', value: 2741 },
  { label: 'Abstract Sepolia Testnet', value: 11124 },
  { label: 'ApeChain Curtis Testnet', value: 33111 },
  { label: 'ApeChain Mainnet', value: 33139 },
  { label: 'Arbitrum Nova Mainnet', value: 42170 },
  { label: 'Arbitrum One Mainnet', value: 42161 },
  { label: 'Arbitrum Sepolia Testnet', value: 421614 },
  { label: 'Avalanche C-Chain', value: 43114 },
  { label: 'Avalanche Fuji Testnet', value: 43113 },
  { label: 'Base Mainnet', value: 8453 },
  { label: 'Base Sepolia Testnet', value: 84532 },
  { label: 'Berachain Mainnet', value: 80094 },
  { label: 'Berachain Bepolia Testnet', value: 80069 },
  { label: 'BitTorrent Chain Mainnet', value: 199 },
  { label: 'BitTorrent Chain Testnet', value: 1029 },
  { label: 'Blast Mainnet', value: 81457 },
  { label: 'Blast Sepolia Testnet', value: 168587773 },
  { label: 'BNB Smart Chain Mainnet', value: 56 },
  { label: 'BNB Smart Chain Testnet', value: 97 },
  { label: 'Celo Alfajores Testnet', value: 44787 },
  { label: 'Celo Mainnet', value: 42220 },
  { label: 'Cronos Mainnet', value: 25 },
  { label: 'Fraxtal Mainnet', value: 252 },
  { label: 'Fraxtal Testnet', value: 2522 },
  { label: 'Gnosis', value: 100 },
  { label: 'HyperEVM Mainnet', value: 999 },
  { label: 'Linea Mainnet', value: 59144 },
  { label: 'Linea Sepolia Testnet', value: 59141 },
  { label: 'Mantle Mainnet', value: 5000 },
  { label: 'Mantle Sepolia Testnet', value: 5003 },
  { label: 'Memecore Testnet', value: 43521 },
  { label: 'Moonbase Alpha Testnet', value: 1287 },
  { label: 'Monad Testnet', value: 10143 },
  { label: 'Moonbeam Mainnet', value: 1284 },
  { label: 'Moonriver Mainnet', value: 1285 },
  { label: 'OP Mainnet', value: 10 },
  { label: 'OP Sepolia Testnet', value: 11155420 },
  { label: 'Polygon Amoy Testnet', value: 80002 },
  { label: 'Polygon zkEVM Cardona Testnet', value: 2442 },
  { label: 'Polygon zkEVM Mainnet', value: 1101 },
  { label: 'Polygon Mainnet', value: 137 },
  { label: 'Katana Mainnet', value: 747474 },
  { label: 'Sei Mainnet', value: 1329 },
  { label: 'Sei Testnet', value: 1328 },
  { label: 'Scroll Mainnet', value: 534352 },
  { label: 'Scroll Sepolia Testnet', value: 534351 },
  { label: 'Sonic Testnet', value: 14601 },
  { label: 'Sonic Mainnet', value: 146 },
  { label: 'Sophon Mainnet', value: 50104 },
  { label: 'Sophon Sepolia Testnet', value: 531050104 },
  { label: 'Swellchain Mainnet', value: 1923 },
  { label: 'Swellchain Testnet', value: 1924 },
  { label: 'Taiko Hekla L2 Testnet', value: 167009 },
  { label: 'Taiko Mainnet', value: 167000 },
  { label: 'Unichain Mainnet', value: 130 },
  { label: 'Unichain Sepolia Testnet', value: 1301 },
  { label: 'World Mainnet', value: 480 },
  { label: 'World Sepolia Testnet', value: 4801 },
  { label: 'XDC Apothem Testnet', value: 51 },
  { label: 'XDC Mainnet', value: 50 },
  { label: 'zkSync Mainnet', value: 324 },
  { label: 'zkSync Sepolia Testnet', value: 300 },
  { label: 'opBNB Mainnet', value: 204 },
  { label: 'opBNB Testnet', value: 5611 },
]

export default networkOptions
